name: forum_app
description: The DSC NSEC Forum is a platform for discussion of technical queries, new technology topics and much more.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  font_awesome_flutter: ^8.5.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Google Sans
      fonts:
        - asset: ./assets/fonts/GoogleSans-Regular.ttf
        - asset: ./assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: ./assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: ./assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/GoogleSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: ./assets/fonts/GoogleSans-MediumItalic.ttf
          style: italic
          weight: 500
    - family: Roboto
      fonts:
        - asset: ./assets/fonts/Roboto-Regular.ttf
        - asset: ./assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: ./assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: ./assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: ./assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: ./assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
